import {
  Bot,
  Code2,
  Globe,
  Smartphone,
  SquareTerminal,
  Terminal,
  Search,
  GraduationCap,
  PenLine,
  Zap,
  Image,
  WandSparkles,
  Video,
  Film,
  AudioLines,
  Music2,
  Palette,
  Presentation,
  BriefcaseBusiness,
  Megaphone,
  Workflow,
  Network,
  ChartNoAxesCombined,
  FileText,
  Braces,
  Monitor,
  type LucideIcon,
} from "lucide-react";
export interface Category {
  name: string;
  slug: string;
  description: string;
  icon: LucideIcon;
  featured: boolean;
  tool_count: number;
}
const definitions: [string, string, string, LucideIcon][] = [
  ["AI Assistants", "ai-assistants", "A little help. A lot more possibility.", Bot],
  ["Coding", "coding", "Write, debug, and build better software.", Code2],
  ["Website Building", "website-building", "Turn your ideas into live websites.", Globe],
  ["Mobile App Building", "mobile-app-building", "Bring your next app idea to life.", Smartphone],
  ["AI Code Editors", "ai-code-editors", "Intelligence, right inside your editor.", SquareTerminal],
  ["AI CLI", "ai-cli", "Your terminal, with an extra pair of hands.", Terminal],
  ["Research", "research", "Go deeper. Find answers that matter.", Search],
  ["Education", "education", "Learn something new, your way.", GraduationCap],
  ["Writing", "writing", "Find the words you were looking for.", PenLine],
  ["Productivity", "productivity", "Less busywork. More meaningful work.", Zap],
  ["Image Generation", "image-generation", "Make the impossible picture possible.", Image],
  ["Image Editing", "image-editing", "Give every image a new perspective.", WandSparkles],
  ["Video Generation", "video-generation", "From an idea to a moving picture.", Video],
  ["Video Editing", "video-editing", "Make your next cut a little smarter.", Film],
  ["Voice & Audio", "voice-audio", "Give your ideas a voice.", AudioLines],
  ["Music", "music", "Explore a new world of sound.", Music2],
  ["Design", "design", "A new creative partner for your process.", Palette],
  ["Presentations", "presentations", "Make your next idea stand out.", Presentation],
  ["Business", "business", "Work smarter, from strategy to execution.", BriefcaseBusiness],
  ["Marketing", "marketing", "Connect your ideas with your audience.", Megaphone],
  ["Automation", "automation", "Put the repetitive work on autopilot.", Workflow],
  ["AI Agents", "ai-agents", "Explore tools that take the next step.", Network],
  ["Data Analysis", "data-analysis", "Turn your data into understanding.", ChartNoAxesCombined],
  ["PDF & Document Tools", "pdf-document-tools", "Get more out of every document.", FileText],
  ["AI APIs", "ai-apis", "Build intelligence into your product.", Braces],
  ["Local AI", "local-ai", "Run AI on your own machine.", Monitor],
];
export const platformList = [
  "Web",
  "Android",
  "iOS",
  "Windows",
  "macOS",
  "Linux",
  "CLI",
  "Browser Extension",
  "Desktop",
  "API",
] as const;
export interface Tool {
  id: string;
  name: string;
  slug: string;
  logo: string;
  company: string;
  short_description: string;
  long_description: string;
  official_url: string;
  categories: string[];
  tags: string[];
  best_for: string[];
  target_users: string[];
  getting_started: string[];
  key_features: string[];
  strengths: string[];
  limitations: string[];
  platforms: string[];
  pricing_type: string;
  free_plan: boolean | null;
  open_source: boolean;
  api_available: boolean | null;
  skill_level: string;
  featured: boolean;
  verified: boolean;
  verification_status: "Not verified" | "Verified";
  last_verified: string | null;
  launch_year: number | null;
  history: string;
  alternatives: string[];
  created_at: string;
  updated_at: string;
  capabilities: string[];
  demo: boolean;
  popularity: number;
}
type Rec = [
  name: string,
  slug: string,
  description: string,
  categories: string[],
  tags: string[],
  url: string,
  company: string,
  year: number | null,
  platforms: string[],
  openSource: boolean,
  api: boolean | null,
];
const W = ["Web"],
  ALL = ["Web", "Android", "iOS", "Windows", "macOS"],
  MOB = ["Web", "Android", "iOS"];
const records: Rec[] = [
  [
    "ChatGPT",
    "chatgpt",
    "A versatile AI assistant for writing, learning, and everyday problem-solving.",
    ["ai-assistants", "writing", "education", "data-analysis", "productivity"],
    ["AI assistant", "Writing", "Everyday tasks"],
    "https://chatgpt.com/",
    "OpenAI",
    2022,
    ALL,
    false,
    true,
  ],
  [
    "Claude",
    "claude",
    "A thoughtful AI assistant for writing, coding, and working through complex ideas.",
    ["ai-assistants", "coding", "research", "writing", "pdf-document-tools"],
    ["Reasoning", "Writing", "Code"],
    "https://claude.ai/",
    "Anthropic",
    2023,
    ALL,
    false,
    true,
  ],
  [
    "Lovable",
    "lovable",
    "Build websites and web applications by describing what you want to create.",
    ["website-building", "coding", "design"],
    ["App builder", "Full stack", "No-code"],
    "https://lovable.dev/",
    "Lovable",
    null,
    W,
    false,
    null,
  ],
  [
    "Cursor",
    "cursor",
    "An AI-powered code editor that helps you write, understand, and improve code.",
    ["ai-code-editors", "coding", "ai-agents"],
    ["Code editor", "Development", "AI coding"],
    "https://cursor.com/",
    "Anysphere",
    2023,
    ["Windows", "macOS", "Linux"],
    false,
    null,
  ],
  [
    "Perplexity",
    "perplexity",
    "Explore questions and discover information with an AI-powered search experience.",
    ["research", "ai-assistants", "education"],
    ["Search", "Research", "Answers"],
    "https://www.perplexity.ai/",
    "Perplexity AI",
    2022,
    MOB,
    false,
    true,
  ],
  [
    "Midjourney",
    "midjourney",
    "Explore visual ideas and create images from natural-language prompts.",
    ["image-generation", "design"],
    ["Text to image", "Creative", "Art"],
    "https://www.midjourney.com/",
    "Midjourney",
    2022,
    W,
    false,
    null,
  ],
  [
    "Runway",
    "runway",
    "AI-powered creative tools for generating and working with video.",
    ["video-generation", "video-editing", "image-generation"],
    ["Video", "Creative", "Generative AI"],
    "https://runwayml.com/",
    "Runway",
    null,
    W,
    false,
    null,
  ],
  [
    "ElevenLabs",
    "elevenlabs",
    "Create and work with AI-generated voices and audio.",
    ["voice-audio", "ai-apis"],
    ["Voice", "Text to speech", "Audio"],
    "https://elevenlabs.io/",
    "ElevenLabs",
    null,
    ["Web", "API"],
    false,
    true,
  ],
  [
    "Gamma",
    "gamma",
    "Create presentations and visual documents with AI assistance.",
    ["presentations", "design", "business"],
    ["Presentations", "Documents", "Visual storytelling"],
    "https://gamma.app/",
    "Gamma",
    null,
    W,
    false,
    null,
  ],
  [
    "Suno",
    "suno",
    "Explore music creation with AI, from a prompt to a song.",
    ["music", "voice-audio"],
    ["Music", "Creative", "Songs"],
    "https://suno.com/",
    "Suno",
    null,
    W,
    false,
    null,
  ],
  [
    "Notion AI",
    "notion-ai",
    "AI assistance for working with notes, documents, and team knowledge.",
    ["productivity", "writing", "business", "pdf-document-tools"],
    ["Workspace", "Notes", "Team knowledge"],
    "https://www.notion.com/product/ai",
    "Notion",
    null,
    ALL,
    false,
    null,
  ],
  [
    "Replit",
    "replit",
    "Build and develop applications in a collaborative, AI-assisted environment.",
    ["website-building", "coding", "mobile-app-building", "ai-agents"],
    ["App builder", "Development", "Cloud"],
    "https://replit.com/",
    "Replit",
    null,
    MOB,
    false,
    null,
  ],
  [
    "n8n",
    "n8n",
    "Connect applications and design workflows for repeatable tasks.",
    ["automation", "ai-agents", "business"],
    ["Workflows", "Integrations", "Automation"],
    "https://n8n.io/",
    "n8n",
    null,
    W,
    false,
    null,
  ],
  [
    "Ollama",
    "ollama",
    "Run and work with language models on your own machine.",
    ["local-ai", "ai-cli", "ai-apis"],
    ["Local models", "Developer tools", "CLI"],
    "https://ollama.com/",
    "Ollama",
    null,
    ["Windows", "macOS", "Linux", "CLI", "API"],
    true,
    true,
  ],
  [
    "Adobe Firefly",
    "adobe-firefly",
    "Explore generative AI tools for creating and editing visual content.",
    ["image-generation", "image-editing", "design", "marketing"],
    ["Images", "Creative", "Editing"],
    "https://www.adobe.com/products/firefly.html",
    "Adobe",
    2023,
    W,
    false,
    null,
  ],
  [
    "Gemini",
    "gemini",
    "An AI assistant for exploring ideas, writing, and everyday questions.",
    ["ai-assistants", "education", "research", "productivity"],
    ["AI assistant", "Learning", "Ideas"],
    "https://gemini.google.com/",
    "Google",
    null,
    MOB,
    false,
    true,
  ],
  [
    "GitHub Copilot",
    "github-copilot",
    "An AI pair programmer that suggests code and answers questions inside your tools.",
    ["coding", "ai-code-editors", "ai-agents"],
    ["AI coding", "Code completion", "Development"],
    "https://github.com/features/copilot",
    "GitHub",
    2021,
    W,
    false,
    null,
  ],
  [
    "Claude Code",
    "claude-code",
    "An agentic coding tool that works with your codebase from the terminal.",
    ["ai-cli", "coding", "ai-agents"],
    ["CLI", "AI coding", "Agents"],
    "https://www.anthropic.com/claude-code",
    "Anthropic",
    2025,
    ["CLI"],
    false,
    null,
  ],
  [
    "Gemini CLI",
    "gemini-cli",
    "An open-source AI agent that brings Gemini into your terminal.",
    ["ai-cli", "coding", "ai-agents"],
    ["CLI", "Open source", "AI coding"],
    "https://github.com/google-gemini/gemini-cli",
    "Google",
    2025,
    ["CLI"],
    true,
    null,
  ],
  [
    "Aider",
    "aider",
    "AI pair programming in your terminal, working directly with your git repository.",
    ["ai-cli", "coding"],
    ["CLI", "Open source", "AI coding"],
    "https://aider.chat/",
    "Aider",
    null,
    ["CLI"],
    true,
    null,
  ],
  [
    "Windsurf",
    "windsurf",
    "An AI-native code editor built around agentic coding workflows.",
    ["ai-code-editors", "coding", "ai-agents"],
    ["Code editor", "AI coding", "Agents"],
    "https://windsurf.com/",
    "Windsurf",
    null,
    ["Windows", "macOS", "Linux"],
    false,
    null,
  ],
  [
    "Bolt.new",
    "bolt-new",
    "Prompt, run, edit, and deploy full-stack web apps in the browser.",
    ["website-building", "coding"],
    ["App builder", "Full stack", "Browser"],
    "https://bolt.new/",
    "StackBlitz",
    null,
    W,
    false,
    null,
  ],
  [
    "v0",
    "v0",
    "Generate user interfaces and web apps from natural-language prompts.",
    ["website-building", "design", "coding"],
    ["UI generation", "App builder", "Web"],
    "https://v0.dev/",
    "Vercel",
    null,
    W,
    false,
    null,
  ],
  [
    "Framer",
    "framer",
    "Design and publish websites with AI-assisted creation tools.",
    ["website-building", "design"],
    ["Websites", "No-code", "Design"],
    "https://www.framer.com/",
    "Framer",
    null,
    W,
    false,
    null,
  ],
  [
    "FlutterFlow",
    "flutterflow",
    "Build mobile and web apps visually, with AI-assisted features.",
    ["mobile-app-building", "website-building"],
    ["Mobile apps", "Low-code", "App builder"],
    "https://www.flutterflow.io/",
    "FlutterFlow",
    null,
    W,
    false,
    null,
  ],
  [
    "Microsoft Copilot",
    "microsoft-copilot",
    "An AI companion for questions, writing, and everyday tasks.",
    ["ai-assistants", "productivity"],
    ["AI assistant", "Everyday tasks", "Writing"],
    "https://copilot.microsoft.com/",
    "Microsoft",
    2023,
    MOB,
    false,
    null,
  ],
  [
    "DeepSeek",
    "deepseek",
    "An AI assistant and model family for chat, reasoning, and coding.",
    ["ai-assistants", "coding", "ai-apis"],
    ["AI assistant", "Reasoning", "Models"],
    "https://www.deepseek.com/",
    "DeepSeek",
    null,
    MOB,
    false,
    true,
  ],
  [
    "Le Chat",
    "le-chat",
    "Mistral AI’s assistant for chat, research, and everyday work.",
    ["ai-assistants", "research"],
    ["AI assistant", "Research", "Chat"],
    "https://chat.mistral.ai/",
    "Mistral AI",
    null,
    MOB,
    false,
    null,
  ],
  [
    "Elicit",
    "elicit",
    "An AI research assistant for finding and summarizing academic papers.",
    ["research", "education"],
    ["Academic research", "Papers", "Summaries"],
    "https://elicit.com/",
    "Elicit",
    null,
    W,
    false,
    null,
  ],
  [
    "Consensus",
    "consensus",
    "An AI search engine that finds answers in scientific research.",
    ["research", "education"],
    ["Scientific research", "Search", "Evidence"],
    "https://consensus.app/",
    "Consensus",
    null,
    W,
    false,
    null,
  ],
  [
    "NotebookLM",
    "notebooklm",
    "A research notebook that helps you understand your own sources.",
    ["research", "education", "pdf-document-tools"],
    ["Research", "Sources", "Summaries"],
    "https://notebooklm.google.com/",
    "Google",
    2023,
    W,
    false,
    null,
  ],
  [
    "Khanmigo",
    "khanmigo",
    "An AI tutor and teaching assistant from Khan Academy.",
    ["education", "ai-assistants"],
    ["Tutoring", "Learning", "Teachers"],
    "https://www.khanmigo.ai/",
    "Khan Academy",
    2023,
    W,
    false,
    null,
  ],
  [
    "Grammarly",
    "grammarly",
    "AI writing assistance for clearer, more confident communication.",
    ["writing", "productivity"],
    ["Writing", "Grammar", "Editing"],
    "https://www.grammarly.com/",
    "Grammarly",
    null,
    ["Web", "Browser Extension", "Windows", "macOS"],
    false,
    null,
  ],
  [
    "Jasper",
    "jasper",
    "An AI platform for marketing content and brand-consistent writing.",
    ["marketing", "writing", "business"],
    ["Marketing", "Copywriting", "Brand voice"],
    "https://www.jasper.ai/",
    "Jasper",
    null,
    W,
    false,
    null,
  ],
  [
    "Otter.ai",
    "otter-ai",
    "AI meeting notes, transcription, and summaries.",
    ["productivity", "voice-audio", "business"],
    ["Transcription", "Meetings", "Notes"],
    "https://otter.ai/",
    "Otter.ai",
    null,
    MOB,
    false,
    null,
  ],
  [
    "Zapier",
    "zapier",
    "Automate work across apps with workflows and AI features.",
    ["automation", "business", "ai-agents"],
    ["Workflows", "Integrations", "No-code"],
    "https://zapier.com/",
    "Zapier",
    null,
    W,
    false,
    null,
  ],
  [
    "Make",
    "make",
    "Visually build and automate workflows across your apps.",
    ["automation", "business"],
    ["Workflows", "Integrations", "Visual builder"],
    "https://www.make.com/",
    "Make",
    null,
    W,
    false,
    null,
  ],
  [
    "Canva",
    "canva",
    "A design platform with AI tools for graphics, presentations, and more.",
    ["design", "presentations", "image-editing", "marketing"],
    ["Design", "Templates", "Creative"],
    "https://www.canva.com/",
    "Canva",
    null,
    ALL,
    false,
    null,
  ],
  [
    "Beautiful.ai",
    "beautiful-ai",
    "Presentation software that uses AI to help design slides.",
    ["presentations", "business"],
    ["Presentations", "Slides", "Design"],
    "https://www.beautiful.ai/",
    "Beautiful.ai",
    null,
    W,
    false,
    null,
  ],
  [
    "Leonardo.Ai",
    "leonardo-ai",
    "Generate images and visual assets with AI models and tools.",
    ["image-generation", "design"],
    ["Text to image", "Creative", "Assets"],
    "https://leonardo.ai/",
    "Leonardo.Ai",
    null,
    W,
    false,
    null,
  ],
  [
    "Krea",
    "krea",
    "Real-time AI image generation, enhancement, and creative tools.",
    ["image-generation", "image-editing", "video-generation"],
    ["Images", "Upscaling", "Creative"],
    "https://www.krea.ai/",
    "Krea",
    null,
    W,
    false,
    null,
  ],
  [
    "Photoroom",
    "photoroom",
    "AI photo editing for product images, backgrounds, and more.",
    ["image-editing", "marketing"],
    ["Photo editing", "Backgrounds", "Products"],
    "https://www.photoroom.com/",
    "Photoroom",
    null,
    MOB,
    false,
    null,
  ],
  [
    "Pika",
    "pika",
    "Turn ideas and images into short AI-generated videos.",
    ["video-generation", "design"],
    ["Video", "Creative", "Text to video"],
    "https://pika.art/",
    "Pika",
    null,
    W,
    false,
    null,
  ],
  [
    "Synthesia",
    "synthesia",
    "Create videos with AI avatars and voices from text.",
    ["video-generation", "business", "education"],
    ["AI avatars", "Video", "Training"],
    "https://www.synthesia.io/",
    "Synthesia",
    null,
    W,
    false,
    null,
  ],
  [
    "Descript",
    "descript",
    "Edit video and audio by editing the text transcript.",
    ["video-editing", "voice-audio"],
    ["Video editing", "Podcasts", "Transcription"],
    "https://www.descript.com/",
    "Descript",
    null,
    ["Web", "Windows", "macOS"],
    false,
    null,
  ],
  [
    "CapCut",
    "capcut",
    "Video editing with AI-powered effects, captions, and templates.",
    ["video-editing", "marketing"],
    ["Video editing", "Captions", "Social"],
    "https://www.capcut.com/",
    "CapCut",
    null,
    ALL,
    false,
    null,
  ],
  [
    "Udio",
    "udio",
    "Create music from text prompts with AI.",
    ["music", "voice-audio"],
    ["Music", "Songs", "Creative"],
    "https://www.udio.com/",
    "Udio",
    null,
    W,
    false,
    null,
  ],
  [
    "Julius AI",
    "julius-ai",
    "Analyze data and create charts by chatting with your files.",
    ["data-analysis", "business"],
    ["Data analysis", "Charts", "Spreadsheets"],
    "https://julius.ai/",
    "Julius AI",
    null,
    W,
    false,
    null,
  ],
  [
    "ChatPDF",
    "chatpdf",
    "Ask questions about PDF documents and get answers from them.",
    ["pdf-document-tools", "research"],
    ["PDF", "Documents", "Q&A"],
    "https://www.chatpdf.com/",
    "ChatPDF",
    null,
    W,
    false,
    null,
  ],
  [
    "OpenAI API",
    "openai-api",
    "Developer platform for building with OpenAI models.",
    ["ai-apis", "coding"],
    ["API", "Models", "Developers"],
    "https://platform.openai.com/",
    "OpenAI",
    null,
    ["API"],
    false,
    true,
  ],
  [
    "Hugging Face",
    "hugging-face",
    "A community platform for models, datasets, and AI applications.",
    ["ai-apis", "local-ai", "coding"],
    ["Models", "Datasets", "Open community"],
    "https://huggingface.co/",
    "Hugging Face",
    null,
    ["Web", "API"],
    false,
    true,
  ],
  [
    "LM Studio",
    "lm-studio",
    "Discover, download, and run local language models on your computer.",
    ["local-ai", "ai-apis"],
    ["Local models", "Desktop", "Privacy"],
    "https://lmstudio.ai/",
    "LM Studio",
    null,
    ["Windows", "macOS", "Linux"],
    false,
    null,
  ],
];
const desktop = (p: string[]) =>
  p.some((x) => ["Windows", "macOS", "Linux"].includes(x)) ? [...p, "Desktop"] : p;
// Company, launch year and platforms are commonly reported details pending admin review; nothing is marked verified. Pricing is never stated.
export const tools: Tool[] = records.map(
  ([name, slug, description, cats, tags, url, company, year, platforms, openSource, api], i) => {
    const catNames = cats.map((c) => definitions.find((d) => d[1] === c)?.[0] ?? c);
    return {
      id: slug,
      name,
      slug,
      logo: slug,
      company,
      short_description: description,
      long_description: `${description} ${name} is listed in ${catNames.slice(0, 3).join(", ")}. Visit the official website for current features, plans, and documentation.`,
      official_url: url,
      categories: cats,
      tags,
      best_for: tags,
      target_users: catNames.map((n) => `People working on ${n.toLowerCase()}`).slice(0, 3),
      getting_started: [
        `Open the official ${name} website.`,
        "Review current plans, terms, and account requirements.",
        "Start with a small, real task to see if it fits your work.",
        "Compare with an alternative before committing.",
      ],
      key_features: tags,
      strengths: catNames.slice(0, 3).map((n) => `Relevant for ${n}`),
      limitations: [
        "Features, pricing, and availability change often—confirm on the official website.",
        "Details on this page have not yet been verified by an administrator.",
      ],
      platforms: desktop(platforms),
      pricing_type: "Check official website",
      free_plan: null,
      open_source: openSource,
      api_available: api,
      skill_level:
        /cli|apis|code-editors/.test(cats[0] ?? "") || slug === "n8n" ? "Advanced" : "Beginner",
      featured: i < 8,
      verified: false,
      verification_status: "Not verified",
      last_verified: null,
      launch_year: year,
      history: year
        ? `${name} is developed by ${company}; publicly launched in ${year} (reported, not verified).`
        : `${name} is developed by ${company}. History not verified yet.`,
      alternatives: [],
      created_at: `2026-09-${String((i % 28) + 1).padStart(2, "0")}T00:00:00Z`,
      updated_at: "2026-10-07T00:00:00Z",
      capabilities: tags,
      demo: true,
      popularity: 100 - i,
    };
  },
);
tools.forEach((t) => {
  t.alternatives = tools
    .filter((x) => x.id !== t.id && x.categories[0] === t.categories[0])
    .concat(
      tools.filter(
        (x) =>
          x.id !== t.id &&
          x.categories[0] !== t.categories[0] &&
          x.categories.includes(t.categories[0]!),
      ),
    )
    .slice(0, 4)
    .map((x) => x.slug);
});
export const categories: Category[] = definitions.map(([name, slug, description, icon], i) => ({
  name,
  slug,
  description,
  icon,
  featured: [0, 1, 2, 6, 10, 12, 14, 20].includes(i),
  tool_count: tools.filter((t) => t.categories.includes(slug)).length,
}));
export const getCategory = (slug: string | undefined) => categories.find((c) => c.slug === slug);
export const getTool = (slug: string) => tools.find((t) => t.slug === slug);
export const taskPresets = [
  { label: "Build a website", category: "website-building" },
  { label: "Write code", category: "coding" },
  { label: "Create images", category: "image-generation" },
  { label: "Research a topic", category: "research" },
  { label: "Analyze a PDF", category: "pdf-document-tools" },
  { label: "Make a presentation", category: "presentations" },
  { label: "Edit a video", category: "video-editing" },
];
export const emptyFilters = {
  q: "",
  category: "",
  tag: "",
  pricing: "",
  source: "",
  platform: "",
  skill: "",
  sort: "popular",
};
export type Filters = typeof emptyFilters;
export function filterTools(items: Tool[], filters: Filters) {
  const q = filters.q.trim().toLowerCase();
  return items
    .filter(
      (t) =>
        (!q ||
          [
            t.name,
            t.short_description,
            ...t.tags,
            ...t.categories.map((c) => getCategory(c)?.name ?? ""),
          ]
            .join(" ")
            .toLowerCase()
            .includes(q)) &&
        (!filters.category || t.categories.includes(filters.category)) &&
        (!filters.tag || t.tags.includes(filters.tag)) &&
        (!filters.source || t.open_source) &&
        (!filters.platform || t.platforms.includes(filters.platform)) &&
        (!filters.skill || t.skill_level === filters.skill),
    )
    .sort((a, b) =>
      filters.sort === "az"
        ? a.name.localeCompare(b.name)
        : filters.sort === "newest"
          ? b.created_at.localeCompare(a.created_at)
          : b.popularity - a.popularity,
    );
}
