// This file is auto-generated by Lovable. Do not modify it.
// Lovable auth integration — Supabase removed in favor of Firebase Auth.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      // Note: Session management is now handled exclusively via Firebase Auth
      // (see src/lib/firebase.ts and src/hooks/use-auth.tsx).
      // If result.tokens need to be sync'd to Firebase, add a custom token
      // exchange via Firebase Admin SDK server-side.
      return result;
    },
  },
};
