/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FindRouteImport } from './routes/find'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminFeaturedRouteImport } from './routes/admin/featured'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'
import { Route as AdminToolsIndexRouteImport } from './routes/admin/tools/index'
import { Route as AdminToolsNewRouteImport } from './routes/admin/tools/new'
import { Route as AdminToolsSlugEditRouteImport } from './routes/admin/tools/$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedRoute = AdminFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsIndexRoute = AdminToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsNewRoute = AdminToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsSlugEditRoute = AdminToolsSlugEditRouteImport.update({
  id: '/tools/$slug/edit',
  path: '/tools/$slug/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/tools/$slug/edit': typeof AdminToolsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/tools': typeof AdminToolsIndexRoute
  '/admin/tools/$slug/edit': typeof AdminToolsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/tools/$slug/edit': typeof AdminToolsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/categories'
    | '/changelog'
    | '/compare'
    | '/discover'
    | '/faq'
    | '/find'
    | '/privacy'
    | '/saved'
    | '/submit'
    | '/terms'
    | '/admin/categories'
    | '/admin/featured'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tags'
    | '/category/$slug'
    | '/tool/$slug'
    | '/admin/'
    | '/admin/tools/new'
    | '/admin/tools/'
    | '/admin/tools/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/categories'
    | '/changelog'
    | '/compare'
    | '/discover'
    | '/faq'
    | '/find'
    | '/privacy'
    | '/saved'
    | '/submit'
    | '/terms'
    | '/admin/categories'
    | '/admin/featured'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tags'
    | '/category/$slug'
    | '/tool/$slug'
    | '/admin'
    | '/admin/tools/new'
    | '/admin/tools'
    | '/admin/tools/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/categories'
    | '/changelog'
    | '/compare'
    | '/discover'
    | '/faq'
    | '/find'
    | '/privacy'
    | '/saved'
    | '/submit'
    | '/terms'
    | '/admin/categories'
    | '/admin/featured'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tags'
    | '/category/$slug'
    | '/tool/$slug'
    | '/admin/'
    | '/admin/tools/new'
    | '/admin/tools/'
    | '/admin/tools/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  FindRoute: typeof FindRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured': {
      id: '/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AdminFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools/': {
      id: '/admin/tools/'
      path: '/tools'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AdminToolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools/new': {
      id: '/admin/tools/new'
      path: '/tools/new'
      fullPath: '/admin/tools/new'
      preLoaderRoute: typeof AdminToolsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools/$slug/edit': {
      id: '/admin/tools/$slug/edit'
      path: '/tools/$slug/edit'
      fullPath: '/admin/tools/$slug/edit'
      preLoaderRoute: typeof AdminToolsSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFeaturedRoute: typeof AdminFeaturedRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminToolsNewRoute: typeof AdminToolsNewRoute
  AdminToolsIndexRoute: typeof AdminToolsIndexRoute
  AdminToolsSlugEditRoute: typeof AdminToolsSlugEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFeaturedRoute: AdminFeaturedRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminToolsNewRoute: AdminToolsNewRoute,
  AdminToolsIndexRoute: AdminToolsIndexRoute,
  AdminToolsSlugEditRoute: AdminToolsSlugEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  FindRoute: FindRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ToolSlugRoute: ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
